### Promise
- 异步编程的一种解决方案,比传统的'回调函数和事件'更合理更强大
- Promise对象代表一个异步操作,有3种状态: pending(进行中)、fulfilled(已成功)和rejected(已失败)
- Primise对象有2个特点：
  - 1.对象的状态不受外界影响
    - 只有异步操作结果可以决定当前是哪种状态
    - “承诺”,表示其他手段无法改变
  - 2.一旦状态改变,就不会再变
    - 状态改变只有2种可能:从pending->fulfilled,从pedding->rejected
    - 状态改变了,在对Promise添加回调函数,会立即得到结果

#### Promise新建后会立即执行
```js
const p1 = new Promise((resolve) => {
  // 里面的内容会立即执行
  console.log('123');
  setTimeout(() => {
    resolve('abc');
  }, 1000);
});
p1.then(value => {
  console.log(value); // abc
});
```

#### Promise相互依赖
- p2的回调函数会等待p1的状态改变,如果p1的状态是resolved或rejected,那么p2的回调函数会立刻执行
- 调用resolve或reject后,Promise的使命就完成了,后续操作应放到then方法里面,最好在resolve前加return
```js
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => reject('error'), 3000);
});
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => resolve(p1), 1000);
});
p2
  .then(
    value => console.log('resolve:' + value),
    errro => console.log('11111'), // 11111
  )
  .catch(error => console.log('reject:' + error));
```

#### Promise.prototype.then()
- then方法返回一个新的Promise实例(注意:不是原来那个Promise实例).因此可以采用链式写法,then后面调用另一个then方法

```js
// Promise 实例
(() => {
  const f1 = async () => {
    const res = await new Promise((resolve) => {
      setTimeout(() => { resolve('p1'); }, 1000);
    });
    return [res, 'p2'];
  };
  f1().then(res => {
    console.log(res);
  }).catch(err => {
    console.log(err)
  });
})();
```

#### Promise.prototype.catch()
- *是 .then(null, rejection) 或 .then(undefined, rejection) 的别名,用于指定发送错误时的回调函数*
- 跟传统的 try/catch 代码块不同的是,如果没有catch()方法,Promise抛出的错误不会传递到外层,即不会有任何反应
- Promise内部的错误(如变量未定义),不会影响到Promise外部的代码,通俗的说法是Promise会吃掉错误
- reject() 方法的作用,等同于抛出错误
  ```js
  new Promise((resolve, reject) => {
    throw new Error('test');
  });
  // 等价于
  new Promise((resolve, reject) => {
    reject(new Error('test'));
  });
  ```

#### Promise.prototype.finally()
- finally() 方法是不管 Promise 对象最后状态如何,都会执行的操作

#### 静态方法
- Promise.all(): 实例都变成fulfilled 或 其中一个变成rejected
  - 无法确定所有实例都结束
- Promise.race(): 有个实例率先改变状态,p的状态就跟着改变
  ```js
  // 5秒内未返回结果,就变为rejected
  (Promise.race([
    fetch('/a.js'),
    new Promise((resolve, reject) => setTimeout(() => reject('time out'), 5000)),
  ])).then().catch();
  ```
- Promise.allSettled(): 只有等待所有实例返回结果,不管是fulfilled还是rejected,包装实例才会结束
  ```js
  // 一旦结束,状态总是fulfilled
  Promise.allSettled([
    Promise.resolve(1),
    Promise.reject(-1),
  ]).then(res => {
    console.log(res);
  });
  // 0: {status: "fulfilled", value: 1}
  // 1: {status: "rejected", reason: -1}
  ```
- Promise.any(): 只要实例有一个变成fulfilled状态,包装实例就会变成fulfilled状态
- Promise.resolve(): 将现有对象转换为Promise对象
  - *立即resovle的Promise对象,在本轮事件循环结束时执行,而不是在下一轮事件循环开始时*
    ```js
    setTimeout(() => console.log('3'), 0); // 下一轮事件循环开始时执行
    Promise.resolve().then(() => console.log(2)); // 本轮事件循环结束时执行
    console.log(1);
    // 1 2 3
    ```
  - 参数分为四种情况
  - 1.参数是一个Promise实例: Promise.resolve 将不做任何修改地返回这个实例
  - 2.参数是一个thenable对象: Promise.resolve 会将这个对象转为 Promise 对象,然后立即执行 thenable 对象的函数
    ```js
    let obj1 = { then: (resolve, reject) => resolve(42) };
    Promise.resolve(obj1).then(v => console.log(v)); // 42
    ```
  -3.参数不具备then方法的对象,后根本不是对象: 则返回resolved
    ```js
    const p1 = Promise.resolve('Hello);
    p1.then(v => v); // Hello
    ```
  -4.不带有任何参数:返回resolved
- Promise.reject()
  - *Promise.reject()方法的参数,会原封不动地作为reject的理由,变成后续方法的参数.这点与Promise.resolve方法不一致*








// Promise.all 实例
(() => {
  const p1 = new Promise((resolve, reject) => {
    setTimeout(() => { resolve('p1'); }, 1000);
  });
  const p2 = new Promise((resolve, reject) => {
    setTimeout(() => { resolve('p2'); }, 1000);
  });
  const f1 = async () => {
    const res = await Promise.all([p1, p2]);
    res.push('p3');
    return res;
  };
  f1().then(res => {
    console.log(res);
  }).catch(err => {
    console.log(err)
  });
})();
```


```js
let promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve([1, 2, 3])
  }, 1000)
}).then(res => {
  console.log(res)
}).catch(res => {
  console.log(res)
}).finally(() => {
  console.log('finally')
})
```

// Promise.resolve(value)方法返回一个以给定值解析后的Promise对象
```js
let promise2 = Promise.resolve([1, 2, 3]).then(res => {
  console.log(res)
}).catch(res => {
  console.log(res)
}).finally(() => {
  console.log('finally')
})
```

// Promise.all(iterable) 方法返回一个 Promise 实例，此实例在 iterable 参数内所有的 promise 都“完成（resolved）”或参数中不包含 promise 时回调完成（resolve）
```js
Promise.all([promise1, promise2]).then(res => {
  console.log('then')
}).catch(res => {
  console.log('catch')
})
```

// Promise.race(iterable) 方法返回一个 promise，一旦迭代器中的某个promise解决或拒绝，返回的 promise就会解决或拒绝。
```js
Promise.race([promise1, promise2]).then(res => {
  console.log('then')
}).catch(res => {
  console.log('catch')
})
```

// 链式调用
```js
Promise.resolve('hello').then(res => {
  return new Promise((resolve, reject) => {
    setTimeout(() => { resolve(res + ' word') }, 1000)
  })
}).then(res => {
  console.log(res)
})
```

// 优先级
// setTimeout: 下一轮"事件循环"开始时执行
// Promise.resolve(): 本轮"事件循环"结束时执行
// console.log: 立即执行
```js
setTimeout(() => { console.log(3) }, 0);

Promise.resolve().then(() => { console.log(2) })

new Promise(resolve => console.log(4)) // 优先

for (let i = 0; i < 10000; i++) { console.log(1) }
```

### 例
- 循环 同步 Promise
```js
(async () => {
  for (let i = 1; i <= 10; i++) {
    await new Promise((resolve) => {
      setTimeout(() => {
        console.log(i);
        resolve();
      }, 1000);
    });
  }
})();
```
```js
// 无效,非同步,forEach里的函数只是参数
(() => {
  [1, 2, 3, 4].forEach(async v => {
    await new Promise((resolve) => {
      setTimeout(() => {
        console.log(v);
        resolve();
      }, 1000);
    });
  });
})();
```